export const FETCH_INITIAL_MEMOS = "FETCH_INITIAL_MEMOS";
export const SEND_INITIAL_MEMOS = "SEND_INITIAL_MEMOS";
export const REQUEST_SAVE_MEMOS = "REQUEST_SAVE_MEMOS";
export const SAVE_MEMOS_SUCCESS = "SAVE_MEMOS_SUCCESS";
export const SAVE_MEMOS_FAILED = "SAVE_MEMOS_FAILED";
